services:
  - type: web
    name: newswave
    runtime: php
    plan: free
    buildCommand: |
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      apt-get install -y nodejs
      composer install --no-interaction --prefer-dist --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
